name: JustChat
version: '0.0.4'
main: dev.meyba.justChat.JustChat
api-version: '1.21'
authors: [ Meyba._., Jezevcik20 ]
description: Just a chat plugin.
softdepend: [ PlaceholderAPI, LuckPerms ]

commands:
  chat:
    description: Main command for the JustChat plugin.
    usage: /chat [reload|help|mutechat|msg|reply|mute|unmute]
    aliases: [jc]
    permission: justchat.use
    permission-message: &cYou don't have permission to use this command.
  msg:
    description: Sends a private message to a player.
    usage: /msg <player> <message>
    aliases: [tell, w]
    permission: justchat.msg
  reply:
    description: Replies to the last private message.
    usage: /reply <message>
    aliases: [r]
    permission: justchat.reply
  mute:
    description: Mutes a player.
    usage: /mute <player> [time] [reason]
    permission: justchat.mute
  unmute:
    description: Unmutes a player.
    usage: /unmute <player>
    permission: justchat.unmute
  ignore:
    description: Ignores a player's messages.
    usage: /ignore <player>
    permission: justchat.ignore
  unignore:
    description: Unignores a player's messages.
    usage: /unignore <player>
    permission: justchat.ignore
  clearchat:
    description: Clears the chat.
    usage: /clearchat
    aliases: [cc]
    permission: justchat.clearchat
permissions:
  justchat.use:
    description: Allows a player to use the /chat command.
    default: op
  justchat.reload:
    description: Allows a player to reload the plugin configuration.
    default: op
  justchat.help:
    description: Allows a player to see the help menu.
    default: true
  justchat.color:
    description: Allows a player to use color codes in chat.
    default: false
  justchat.mutechat:
    description: Allows to mute global chat.
    default: op
  justchat.antiswear.bypass:
    description: Allows a player to bypass the anti-swear filter.
    default: op
  justchat.msg:
    description: Allows a player to send private messages.
    default: true
  justchat.reply:
    description: Allows a player to reply to private messages.
    default: true
  justchat.mute:
    description: Allows a player to mute other players.
    default: op
  justchat.unmute:
    description: Allows a player to unmute other players.
    default: op
  justchat.ignore:
    description: Allows a player to ignore other players.
    default: true
  justchat.clearchat:
    description: Allows a player to clear the chat.
    default: op
  justchat.mutechat.bypass:
    description: Allows a player to bypass global chat mute.
    default: op
